# Generated by Django 5.1.5 on 2025-01-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('email', models.EmailField(max_length=150)),
                ('subject', models.CharField(max_length=255, verbose_name='Тема обращения')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('ticket_number', models.CharField(blank=True, max_length=55, null=True, verbose_name='Номер заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
